language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install --upgrade pip && pip install -r requirements.txt
    - python3 setup.py build_ext --inplace

# TODO : flake8/linting, 

# For now the setup just downloads the cifar10 data
script:
    - setup.sh
    - python3 tests/test_fcnet.py
    - python3 tests/test_convnet.py
    - python3 tests/test_solver.py
